WARNING:passlib.handlers.bcrypt:(trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\hugogarsan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
INFO:root:2024-04-10 19:07:12.369192 - Inicio de sesión exitoso para usuario: string
INFO:root:2024-04-10 19:07:49.331665 - Inicio de sesión exitoso para usuario: string
WARNING:passlib.handlers.bcrypt:(trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\hugogarsan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
INFO:root:2024-04-11 18:18:35.898722 - Inicio de sesión exitoso para usuario: string
WARNING:passlib.handlers.bcrypt:(trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\hugogarsan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
WARNING:passlib.handlers.bcrypt:(trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\hugogarsan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
INFO:root:2024-04-12 17:33:45.808071 - Intento de inicio de sesión fallido para usuario: hugog
INFO:root:2024-04-12 17:42:53.102527 - Intento de inicio de sesión fallido para usuario: antonieta
INFO:root:2024-04-12 17:43:11.017880 - Intento de inicio de sesión fallido para usuario: hugog
INFO:root:2024-04-12 17:43:16.660494 - Intento de inicio de sesión fallido para usuario: hugogarsan
INFO:root:2024-04-12 17:46:53.905810 - Intento de inicio de sesión fallido para usuario: hugog
INFO:root:2024-04-12 17:47:03.915731 - Intento de inicio de sesión fallido para usuario: hugog
INFO:root:2024-04-12 17:53:06.063233 - Intento de inicio de sesión fallido para usuario: hugogarsan
INFO:root:2024-04-12 18:12:26.853995 - Intento de inicio de sesión fallido para usuario: 
INFO:root:2024-04-12 18:43:41.795474 - Intento de inicio de sesión fallido para usuario: hugog
INFO:root:2024-04-12 18:47:23.391692 - Intento de inicio de sesión fallido para usuario: hugofasfa
INFO:root:2024-04-12 18:47:35.486190 - Intento de inicio de sesión fallido para usuario: hugog
INFO:root:2024-04-12 18:47:40.654913 - Intento de inicio de sesión fallido para usuario: hugogarsan
INFO:root:2024-04-12 18:48:16.107970 - Intento de inicio de sesión fallido para usuario: String
INFO:root:2024-04-12 18:52:02.855257 - Intento de inicio de sesión fallido para usuario: String
INFO:root:2024-04-12 18:52:14.273495 - Intento de inicio de sesión fallido para usuario: hugog
INFO:root:2024-04-12 18:52:21.463118 - Intento de inicio de sesión fallido para usuario: hugog
WARNING:passlib.handlers.bcrypt:(trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\hugogarsan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
INFO:root:2024-04-12 18:53:28.777161 - Intento de inicio de sesión fallido para usuario: hugo123
INFO:root:2024-04-12 18:53:49.295655 - Intento de inicio de sesión fallido para usuario: hugo123
INFO:root:2024-04-12 19:01:30.306207 - Intento de inicio de sesión fallido para usuario: hugo123
WARNING:passlib.handlers.bcrypt:(trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\hugogarsan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
WARNING:passlib.handlers.bcrypt:(trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\hugogarsan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_8.2p1)
INFO:paramiko.transport:Authentication (publickey) failed.
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_8.2p1)
INFO:paramiko.transport:Authentication (publickey) failed.
INFO:paramiko.transport:Authentication (password) successful!
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_8.2p1)
INFO:paramiko.transport:Authentication (publickey) failed.
INFO:paramiko.transport:Authentication (password) successful!
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_8.2p1)
INFO:paramiko.transport:Authentication (publickey) failed.
INFO:paramiko.transport:Authentication (password) successful!
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_8.2p1)
INFO:paramiko.transport:Authentication (publickey) failed.
INFO:paramiko.transport:Authentication (password) successful!
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_8.2p1)
INFO:paramiko.transport:Authentication (publickey) failed.
INFO:paramiko.transport:Authentication (password) successful!
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_8.2p1)
INFO:paramiko.transport:Authentication (publickey) failed.
INFO:paramiko.transport:Authentication (password) successful!
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_8.2p1)
INFO:paramiko.transport:Authentication (publickey) failed.
INFO:paramiko.transport:Authentication (password) successful!
WARNING:passlib.handlers.bcrypt:(trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\hugogarsan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_8.2p1)
INFO:paramiko.transport:Authentication (publickey) failed.
INFO:paramiko.transport:Authentication (password) successful!
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_8.2p1)
INFO:paramiko.transport:Authentication (publickey) failed.
INFO:paramiko.transport:Authentication (password) successful!
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_8.2p1)
INFO:paramiko.transport:Authentication (publickey) failed.
INFO:paramiko.transport:Authentication (password) successful!
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_8.2p1)
INFO:paramiko.transport:Authentication (publickey) failed.
INFO:paramiko.transport:Authentication (password) successful!
WARNING:passlib.handlers.bcrypt:(trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\hugogarsan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_8.2p1)
INFO:paramiko.transport:Authentication (publickey) failed.
INFO:paramiko.transport:Authentication (password) successful!
WARNING:passlib.handlers.bcrypt:(trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\hugogarsan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_8.2p1)
INFO:paramiko.transport:Authentication (publickey) failed.
INFO:paramiko.transport:Authentication (password) successful!
ERROR:paramiko.transport:Exception: Error reading SSH protocol banner
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "E:\Project\Back\.venv\Lib\site-packages\paramiko\transport.py", line 2211, in _check_banner
ERROR:paramiko.transport:    buf = self.packetizer.readline(timeout)
ERROR:paramiko.transport:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:paramiko.transport:  File "E:\Project\Back\.venv\Lib\site-packages\paramiko\packet.py", line 380, in readline
ERROR:paramiko.transport:    buf += self._read_timeout(timeout)
ERROR:paramiko.transport:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:paramiko.transport:  File "E:\Project\Back\.venv\Lib\site-packages\paramiko\packet.py", line 622, in _read_timeout
ERROR:paramiko.transport:    raise socket.timeout()
ERROR:paramiko.transport:TimeoutError
ERROR:paramiko.transport:
ERROR:paramiko.transport:During handling of the above exception, another exception occurred:
ERROR:paramiko.transport:
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "E:\Project\Back\.venv\Lib\site-packages\paramiko\transport.py", line 2039, in run
ERROR:paramiko.transport:    self._check_banner()
ERROR:paramiko.transport:  File "E:\Project\Back\.venv\Lib\site-packages\paramiko\transport.py", line 2215, in _check_banner
ERROR:paramiko.transport:    raise SSHException(
ERROR:paramiko.transport:paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
ERROR:paramiko.transport:
INFO:root:2024-04-22 17:40:22.429288 - Login attempt for username: string
INFO:root:2024-04-22 17:40:33.724931 - Login successful for username: string
ERROR:paramiko.transport:Exception: Error reading SSH protocol banner
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "E:\Project\Back\.venv\Lib\site-packages\paramiko\transport.py", line 2211, in _check_banner
ERROR:paramiko.transport:    buf = self.packetizer.readline(timeout)
ERROR:paramiko.transport:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:paramiko.transport:  File "E:\Project\Back\.venv\Lib\site-packages\paramiko\packet.py", line 380, in readline
ERROR:paramiko.transport:    buf += self._read_timeout(timeout)
ERROR:paramiko.transport:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:paramiko.transport:  File "E:\Project\Back\.venv\Lib\site-packages\paramiko\packet.py", line 622, in _read_timeout
ERROR:paramiko.transport:    raise socket.timeout()
ERROR:paramiko.transport:TimeoutError
ERROR:paramiko.transport:
ERROR:paramiko.transport:During handling of the above exception, another exception occurred:
ERROR:paramiko.transport:
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "E:\Project\Back\.venv\Lib\site-packages\paramiko\transport.py", line 2039, in run
ERROR:paramiko.transport:    self._check_banner()
ERROR:paramiko.transport:  File "E:\Project\Back\.venv\Lib\site-packages\paramiko\transport.py", line 2215, in _check_banner
ERROR:paramiko.transport:    raise SSHException(
ERROR:paramiko.transport:paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
ERROR:paramiko.transport:
INFO:root:2024-04-22 18:28:09.764430 - Login attempt for username: string
INFO:root:2024-04-22 18:28:21.175193 - Login successful for username: string
INFO:root:2024-04-22 18:30:08.677397 - Login successful for username: string
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_8.2p1)
INFO:paramiko.transport:Authentication (password) successful!
INFO:root:2024-04-22 18:33:48.519507 - Login successful for username: string
INFO:root:2024-04-22 19:08:45.502577 - Login successful for username: string
INFO:root:2024-04-22 19:09:57.916083 - Login successful for username: string
INFO:root:2024-04-22 19:11:27.076409 - Login successful for username: string
INFO:root:2024-04-22 19:13:32.312293 - Login successful for username: string
INFO:root:2024-04-22 19:14:03.760245 - Login successful for username: string
